language: python
python:
  - "2.7"
  - "3.6"
cache:
  directories:
    - tests/create-react-app/node_modules
    - tests/create-react-app-with-redux/node_modules
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  - NODE_VERSION="8.9.4"
before_install:
  - nvm install $NODE_VERSION
install:
  - pip install -r requirements.txt
  - python setup.py develop
  - (cd tests/create-react-app && yarn install)
  - (cd tests/create-react-app-with-redux && yarn install)
  - sleep 10
before_script:
  - node -v
  - wget "http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 2
script:
- pybot tests
notifications:
  email:
  - stollenwerk@kitconcept.com
