language: node_js
node_js:
- 6.11.5
- 8.6.0
cache:
  directories:
    - tests/create-react-app/node_modules
    - tests/create-react-app-with-redux/node_modules
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 2
install:
- sudo pip install -r requirements.txt
- sudo python setup.py develop
- (cd tests/create-react-app && yarn install)
- (cd tests/create-react-app-with-redux && yarn install)
- sleep 10
script:
- pybot tests
notifications:
  email:
  - stollenwerk@kitconcept.com
